---
- name: Ensure DNS is set to avoid apt issues
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 8.8.8.8'
    insertafter: BOF

- name: Clean apt cache and update package lists
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  retries: 5
  delay: 5
  register: apt_update
  until: apt_update is succeeded
  
- name: Remove apt locks if necessary
  ansible.builtin.shell: |
    rm -f /var/lib/apt/lists/lock
    rm -f /var/cache/apt/archives/lock
    rm -f /var/lib/dpkg/lock*
    dpkg --configure -a
  args:
    executable: /bin/bash
  changed_when: false

- name: Install required packages for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
    force_apt_get: yes
  retries: 5
  delay: 5
  register: apt_install
  until: apt_install is succeeded

- name: Create Docker GPG keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker Engine and Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
    force_apt_get: yes
  retries: 5
  delay: 5
  register: docker_install
  until: docker_install is succeeded

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes